---
#################### YUM ##############################
- name: upgrade packages on RPM based systems
  hosts: all

  tasks:
    - name: install all updates
      yum:
        name: '*'
        state: latest
